config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  
  resources :blogs do
  
  collection do
    post :confirm
  end
  
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  #  validates :title, presence: true, length: {maximum: 140}
  #  validates :content, presence: true, length: {maximum: 140}


  validate :add_error
 
  def add_error
    if title.blank?
      errors[:base] << "タイトルを入力してください"
    end
    
    if title.length >= 140
        errors[:base] << "タイトルは140字以内で入力してください"
    end
 
    if content.blank?
      errors[:base] << "本文を入力してください"
    end

    if content.length >= 140
        errors[:base] << "本文は140字以内で入力してください"
    end

  end
  
end

app/models/contact.rb
class Contact < ApplicationRecord
       validates :name,  presence: true, length: { maximum: 140 } 
       validates :email,  presence: true, length: { maximum: 140 } 
       validates :content,  presence: true, length: { maximum: 140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました!"
    else
      render 'new'
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end
  
  
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to new_contact_path, notice: "問い合わせを作成しました!"
    else
      render 'new'
    end
  end
  
  
  private
  
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit ) do |form| %>
<% if @blog.errors.any? %>
<div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
    <ul>
        
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
</div>
<%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面に戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>

<p>タイトル: <%= @blog.title %></p>
<p>本文: <%= @blog.content %></p>

<%= form.submit "登録する" %>

<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>
<%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<%= notice %>

<table>
    <tr>
        <th>タイトル</th>
        <th>内容</th>
    </tr>
    
    <% @blogs.each do |blog| %>
    <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
        <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
        <td><%= link_to "ブログを削除する", blog_path(blog.id), method: :delete, data: { confirm: "本当に削除していいですか？"} %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'ブログ一覧画面に戻る', '/blogs' %>
<br>
<%= link_to 'ブログ新規作成へ', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

app/views/contacts/_form.html.erb
<%= form_with(model: @contact, local: true, url: contacts_path ) do |form| %>
<% if @contact.errors.any? %>
<div id="error_explanation">
    <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
    <ul>
        
        <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="contact_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<div class="contact_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
</div>

<div class="contact_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
</div>

<%= form.submit %>
<% end %>

app/views/contacts/create.html.erb
<h3>以下の内容で、作成する。</h3>

<%= form_with(model: @contact, url: new_contact_path, local: true) do |form| %>
<%= form.hidden_field :name %>
<%= form.hidden_field :email %>
<%= form.hidden_field :content %>

<p>名前: <%= @contact.name %></p>
<p>メールアドレス: <%= @contact.email %></p>
<p>本文: <%= @contact.content %></p>

<%= form.submit "登録する" %>

<% end %>

app/views/contacts/new.html.erb
<h2>問い合わせを作成する</h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>